### ISSUE TITLE
Push / Upload your Portfolio Webpage

### ISSUE THREAD

**Issue by kschatryajuloya** [kschatryajuloya/IPT2_Grp11_CaseStudy#3]
!! All members must UPLOAD THEIR PORTFOLIO in their OWN feature branch. DO NOT PUSH IN MAIN BRANCH!!

**Comment by kschatryajuloya** [comment]
Comment here "Done" once done uploading. Thank you!

**Comment by ErvinVillamor** [comment]
Done!!

**Comment by ManucumCD12** [comment]
Done na po

**Comment by SeaPraetorian** [comment]
Done na bos

**Comment by DeGuzmanMW08** [comment]
Done na.

**Comment by kschatryajuloya** [comment]
All members successfully uploaded their webpage.

**Comment by SeaPraetorian** [comment]
reuploaded my website in folder, done
